// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvaRQZQGgSBelM_wUBAYwdkh2IeCuV-5c',
    appId: '1:729783140179:web:7fe09df708011b7c936ba6',
    messagingSenderId: '729783140179',
    projectId: 'cmp-walkthrough',
    authDomain: 'cmp-walkthrough.firebaseapp.com',
    storageBucket: 'cmp-walkthrough.appspot.com',
    measurementId: 'G-6ZC11BCDFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnAJAy0HWjwJqGvow5rV_hgqv2BGW6hw',
    appId: '1:729783140179:android:ec0de08b1880c895936ba6',
    messagingSenderId: '729783140179',
    projectId: 'cmp-walkthrough',
    storageBucket: 'cmp-walkthrough.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK_nuzzLPOk50MpGhQlztJITBbylnYSGM',
    appId: '1:729783140179:ios:88317b141c19eab2936ba6',
    messagingSenderId: '729783140179',
    projectId: 'cmp-walkthrough',
    storageBucket: 'cmp-walkthrough.appspot.com',
    iosClientId: '729783140179-bmheub5nklpr6so6gkt5i8rbmpjbi0q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmpTask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK_nuzzLPOk50MpGhQlztJITBbylnYSGM',
    appId: '1:729783140179:ios:a986475c117e4027936ba6',
    messagingSenderId: '729783140179',
    projectId: 'cmp-walkthrough',
    storageBucket: 'cmp-walkthrough.appspot.com',
    iosClientId: '729783140179-runtsikq808h8iubhn3b439ldj36s28m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmpTask1.RunnerTests',
  );
}
